name: CI

on:
  push:
    branches:
      - "main"
jobs:
  build:
    environment:
        name: taverna-de-mordor
        url: https://taverna-de-mordor.herokuapp.com
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run Migrations
        run: node ace migration:run
